name: Build Tauri App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install system dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev libglib2.0-dev libsoup2.4-dev
      
      - name: Install dependencies
        run: npm install
        working-directory: tauri-app

      - name: Install Tauri CLI
        run: npm install -g @tauri-apps/cli
        working-directory: tauri-app

      - name: Build Tauri app
        run: npm run tauri build
        working-directory: tauri-app